openBackhaul/AdministratorAdministration

server/controllers/Core.js
server/controllers/HttpClient.js
server/controllers/HttpServer.js
server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/index.js

Refactor : the security validation machanism for apiKeyAuth and basicAuth validations

---

server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/service/IndividualServicesService.js
server/service/TcpClientService.js
server/service/TcpServerService.js

Fix for (issue#38) OAM layer : Get request responseBody attribute needs to be corrected to view the ipv-4-address of tcp-server and tcp-client

Fix for OAM layer : Get request responseBody attribute needs to be corrected to view the ipv-4-address of tcp-server and tcp-client(issue#38)

---

server/controllers/BasicServices.js
server/controllers/Core.js
server/controllers/HttpClient.js
server/controllers/HttpServer.js
server/controllers/IndividualServices.js
server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/index.js
server/package-lock.json
server/package.json

- using ExecutionAndTraceService and OamLogService from onf-core-model-ap
- using AppCommons from onf-core-model-ap to simplify appliction bootstrap
Fixes #34
Signed-off-by: Martin Sunal <martin.sunal@paxet.io>

Used onf-core-model-ap v1.0.0

---

server/service/individualServices/SoftwareUpgrade.js

Fix for issue#44

---

server/service/IndividualServicesService.js

fix the issue #46 /v1/list-applications : OldRelease and NewRelease data to be removed

fix the issue #46 /v1/list-applications : OldRelease and NewRelease data to be removed 

---

server/api/openapi.yaml

Datatype enumeration value  "String" -> "string"

---

AdministratorAdministration_0.0.2_tsi.211217.1845+data.2.json

userName attribute add to data file

---

AdministratorAdministration+data.json
AdministratorAdministration+services.yaml
AdministratorAdministration.yaml

**Process for updating the UUIDs of Services**
If no errors found

Update UUIDs of Services

---

AdministratorAdministration+config.json
AdministratorAdministration.yaml

Updating the UUIDs of FCs

---

AdministratorAdministration+config.json
AdministratorAdministration+profileInstances.yaml
AdministratorAdministration+profiles.yaml
AdministratorAdministration.yaml

Minimizing the ActionProfile

---

server/service/IndividualServicesService.js

Implementation to be updated in controllers/BasicService for the service redirect-topology-change-information

issue #56 Implementation to be updated in controllers/BasicService for the service redirect-topology-change-information

---

AdministratorAdministration+config.json
AdministratorAdministration+services.yaml

Add protocol attribute at TcpServer and TcpClient

---

AdministratorAdministration+config.json
AdministratorAdministration+services.yaml
AdministratorAdministration.yaml

Update FakeIP addresses and Ports

---

AdministratorAdministration.yaml

Rectify callbacks

---

server/service/IndividualServicesService.js

Support Version 2.0.0 changes for list-application

---

server/api/openapi.yaml
server/database/load.json
server/package.json
server/service/AuthorizationApplication.js
server/service/IndividualServicesService.js
server/service/individualServices/AuthorizationApplication.js

Support Version 2.0.0 changes for approve-oam-request

---

server/controllers/ActionProfile.js
server/controllers/Core.js
server/controllers/FileProfile.js
server/controllers/GenericResponseProfile.js
server/controllers/HttpClient.js
server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/service/ActionProfileService.js
server/service/CoreService.js
server/service/FileProfileService.js
server/service/GenericResponseProfileService.js
server/service/HttpClientService.js
server/service/OperationClientService.js
server/service/OperationServerService.js
server/service/TcpClientService.js
server/service/TcpServerService.js
server/service/individualServices/PrepareForwardingAutomation.js

Implement OAM Services for version 2.0.0

---

server/service/IndividualServicesService.js

correct the required file name of individualservicesoperationsmapping file in IndividualServicesServices.js file

---

server/database/load.json

Update docs/openApi.yaml file with swagger yaml file

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

Resolve Update the Variables and Function changes for the service /v1/bequeath-your-data-and-die

---

server/api/openapi.yaml

Resolve update additionalProperties:false in openapi.yaml file

---

server/service/HttpClientService.js
server/service/OperationClientService.js
server/service/OperationServerService.js
server/service/TcpClientService.js
server/service/TcpServerService.js

Resolve Forwarding  is sent to ALT even value is not updated 

---

server/controllers/BasicServices.js

Resolve  INFORM-ABOUT-APPLICATION-IN-GENERIC-REPRESENTATION Service getting Empty consequentActionList and  responseValueList

---

server/controllers/BasicServices.js

Resolve INFORM-ABOUT-RELEASE-HISTORY-IN-GENERIC-REPRESENTATION Service getting Empty consequentActionList and responseValueList

---

server/service/OperationClientService.js

Resolve operation-client-interface-status/operational-state service getting failed due to openapi.validation

---

testing/AdministratorAdministration+data.json

Update data.json file to testcases v2.0.1

---

server/service/IndividualServicesService.js
server/service/individualServices/AuthorizationApplication.js

Reslove Update the approveOamRequest Service for the file does not exit and ALL method

---

server/service/IndividualServicesService.js

Resolved while executing bequeath-your-data-and-die, updating protocol, address and port are not working

---

server/service/OperationServerService.js
server/service/TcpServerService.js

Resolve while executing  get OperationServerLifeCycleState    and getTcpServerLocalAddress not working as expected

---

server/service/individualServices/AuthorizationApplication.js

Resolve getApplicationDataFile method name changed getApplicationDataFileContent and path has changed so need to change the corresponding references

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

resolve update the bequeathYourDataAndDie method  and sotwareupgrade method

---

server/service/IndividualServicesService.js

Update the approveOamRequest Service for the file does not exit and ALL method

---

server/package.json

alpha.12 upgrade

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

resolve Proposal to use the 'getAllApplicationList' method to from ApplicationPattern

---

server/database/load.json
server/dockerfile
server/package-lock.json
server/package.json

npm package update to alpha.13

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

resolve change the method name  from  resolveHttpTcpAndOperationClientUuidFromForwardingName in the bequeathyourdataanddie service

---

server/package-lock.json
server/package.json

Update the npm packages of BasicServices and ApplicationPattern to 2.0.1-alpha.14

---

server/service/individualServices/SoftwareUpgrade.js

issue-234 : fixed release number taken from http-c instead of http-s

---

server/controllers/ActionProfile.js
server/controllers/BasicServices.js
server/controllers/Core.js
server/controllers/FileProfile.js
server/controllers/GenericResponseProfile.js
server/controllers/HttpClient.js
server/controllers/HttpServer.js
server/controllers/IndividualServices.js
server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/package-lock.json
server/package.json

- added http-errors dependency
- all controllers pass an error to buildResponse and process returned response status code and body

issue 227 changed http error handling in controllers

---

server/controllers/BasicServices.js
server/service/IndividualServicesService.js

Changes related to AP#736

---

server/controllers/BasicServices.js

Resolve /v1/register-yourself service RequestHeaders require changes when RequestBody is empty

---

server/service/IndividualServicesService.js

resolve bequeathYourDataAndDie services is giving 500 internalserver Error

---

server/package-lock.json
server/package.json

Update the npm packages of BasicServices and ApplicationPattern to 2.0.1-alpha.16

---

server/package-lock.json
server/package.json

Resolve Update the npm packages of BasicServices and ApplicationPattern to 2.0.1-alpha.19

---

server/service/IndividualServicesService.js

Resolve /v1/bequeath-your-data-and-die is not sending a notification to  /v1/update-ltp for tcp-client Updation

---

server/index.js
server/package-lock.json
server/package.json

Update alpha.22 package

---

server/application-data/application-data.json

fixes https://github.com/openBackhaul/AdministratorAdministration/issues/204
reviewer is @PrathibaJee

issue204: application-data.json file created for test-suite run

---

server/service/individualServices/SoftwareUpgrade.js

Resolve The request-body formulation for callback bequeath-your-data-and-die should be modified

---

server/service/IndividualServicesService.js

resolve /v1/bequeath-your-data-and-die is not sending a notification to /v1/update-ltp for tcp-client Updation

---

server/controllers/BasicServices.js
server/package-lock.json
server/package.json
server/service/IndividualServicesService.js

issue-283 : use new classes from AP, AP/BS

---

server/package-lock.json
server/package.json

Resolve Update the npm packages of BasicServices and ApplicationPattern to 2.0.2-alpha.2

---

testing/AdministratorAdministration+data.json

resolve Testsuite adjustments

---

server/index.js
server/package-lock.json
server/package.json
server/service/IndividualServicesService.js
server/service/individualServices/AuthorizationApplication.js
server/service/individualServices/PrepareForwardingAutomation.js
server/service/individualServices/RegardApplication.js
server/service/individualServices/regardapplicationcallback.js

To structure the data of application-data to support the /v1/approve-basic-auth-request

---

server/controllers/BasicServices.js

/v1/update-client-of-subsequent-release service is giving 500 internal server Error

---

server/controllers/BasicServices.js

/v1/inform-about-preceding-release service is giving 500 internal server Error

---

server/service/IndividualServicesService.js
server/service/individualServices/RegardApplication.js

Trace indicator is not working as expected for /v1/regard-application service

---

server/service/individualServices/SoftwareUpgrade.js

Trace indicator is not working as expected for /v1/bequeath-your-data-and-die service

---

server/controllers/BasicServices.js

Reverts openBackhaul/AdministratorAdministration#329

Revert "/v1/inform-about-preceding-release service is giving 500 internal server Error"

---

spec/AccessAdministration+config.json
spec/AccessAdministration+profileInstances.yaml

Include ResponseProfiles for new releases (fixes #360)

---

spec/AccessAdministration.yaml

Update ResponseCode in PromptForBequeathingDataCausesTransferOfListOfApplications (fixes #318)
